// Sempurna's question bank — written for Maxime & Ecaa's long-distance
// Paris↔Makassar reality: light and deep, mixed. Deliberately different from
// the Twosprout bank so the two apps never ask the same thing.
//
// SPICY unlocks with the streak (see questions.js) — more intimate, still sweet.
//
// An entry is either a plain string (reads the same for everyone) or an
// object with wording variants:
//   ldr      — base text for long-distance couples (default when a plain
//              string won't do)
//   met      — LDR couple that HAS met in person
//   notMet   — LDR couple that hasn't met yet
//   together — couple living in the same place
// Resolution lives in questions.js (resolveEntry).

/** @type {(string | { met: string, notMet: string })[]} */
export const QUESTIONS = [
	// Light & silly
	"If we opened a tiny warung-café together, what would we sell?",
	"What stereotype from my country fits me perfectly, according to you?",
	"What stereotype from your country fits you perfectly — and do you own it?",
	"If our love story was a movie, what would its title be?",
	"Which emoji is basically me? Defend your choice.",
	"What food from my country are you secretly scared to try?",
	"If we had a pet together, what would we name it?",
	"What's a word in my language that you love saying out loud?",
	"Which of us would survive longer in a zombie apocalypse, honestly?",
	{ ldr: "If we could teleport to each other once a week, which day would you pick and why?",
	  together: "If we could teleport anywhere together once a week, where would we go first?" },
	{ ldr: "What's the weirdest thing you'd put in your suitcase when you finally fly to me?",
	  together: "What's the weirdest thing you'd pack for a surprise weekend away with me?" },
	"If we swapped phones for a day, what's the first thing you'd check?",
	"What ridiculous matching outfit should we wear one day?",
	{ ldr: "If our video calls had an intro song, what would it be?",
	  together: "If our evenings together had an intro song, what would it be?" },
	"Which cartoon couple are we?",
	"What's the most 'us' thing that happened this month?",
	"If you could rename me in your contacts right now, what would it say?",
	"What would our couple YouTube channel be about?",
	"Two plane tickets, anywhere, tomorrow morning — where do we go?",
	"What snack from your country do I absolutely need to taste?",
	"If we were both animals, who'd be chasing whom?",
	"What's a habit of mine you've started copying without noticing?",
	"If we had a secret handshake, what moves would it have?",
	"What's the funniest translation fail we've had?",
	"Which one of us is the chaotic one, really?",
	"If my city had a smell, what do you imagine it smells like?",
	"What's something totally normal in your country that would shock mine?",
	"If we made a playlist called 'us', what are the first three songs?",
	{ ldr: "What tiny thing do I do on video calls that makes you laugh?",
	  together: "What tiny thing do I do around the house that makes you laugh?" },
	"If you woke up in my bed tomorrow (I'm not there, calm down), what would you do first?",

	// Deep & meaningful
	{ ldr: "What's the hardest part of the distance that you don't usually say out loud?",
	  together: "What's something hard about us that you don't usually say out loud?" },
	{ ldr: "When do you miss me the most during a normal day?",
	  together: "When do you think of me the most during a normal day apart?" },
	{ ldr: "What's one thing this distance has taught you about yourself?",
	  together: "What's one thing being with me has taught you about yourself?" },
	{ ldr: "What are you most looking forward to about ordinary life together?",
	  together: "What's your favorite part of our ordinary life together?" },
	"What did you feel the first time we talked?",
	"What's a moment where you thought: okay, this person is different?",
	"What scares you the most about us — and what makes it worth it anyway?",
	"How do you imagine a lazy Sunday for us, five years from now?",
	"What's one thing you've never told me because the timing never felt right?",
	{ ldr: "What does 'home' mean to you now that your heart lives in two countries?",
	  together: "What does 'home' mean to you since we've been us?" },
	"What part of your culture do you most want our future kids to have?",
	"When you can't sleep, what do you think about?",
	"What's a small sacrifice you've made for us that I might not have noticed?",
	"How did you change since we met?",
	"What's something about your family you want me to understand better?",
	"What compliment from me do you replay in your head?",
	{ ldr: "What do you do with the missing, on the heavy days?",
	  together: "What do you need from me most, on the heavy days?" },
	"What tradition should we invent, just for the two of us?",
	"If you could freeze one moment we've lived, which one?",
	"What's a dream you're scared to say out loud in case it doesn't happen?",
	"What do you need more of from me right now?",
	"What's the bravest thing loving me has made you do?",
	"Which version of you do I bring out?",
	"What would you tell the you from the night before we met?",
	"What's one thing about the future that feels certain to you?",
	"What does my voice do to your mood, honestly?",
	"What's the most loved you've ever felt with me?",
	{ ldr: "If the distance ended tomorrow, what's the very first ordinary thing you'd want us to do?",
	  together: "What ordinary thing we do together would you miss the most?" },
	"What's a fear about meeting my family/friends that I can help with?",
	"What part of us do you hope never changes?",

	// Us & memories
	"What's your favorite photo of us (or of me) and why that one?",
	{ ldr: "Which of our video calls do you remember the most?",
	  together: "Which of our late-night conversations do you remember the most?" },
	"What made you laugh the hardest with me?",
	"What's the first thing you noticed about me?",
	"When did you know you were falling?",
	"What's a message from me you've screenshotted or saved?",
	"What detail about me do you notice that nobody else does?",
	"What's our most 'romcom' moment so far?",
	"If you had to describe us in three words, which three?",
	"What's something I taught you without meaning to?",
	"Which future trip together do you daydream about the most?",
	{ ldr: "What's the best gift I could bring in my suitcase — that costs nothing?",
	  together: "What's the best gift I could give you — that costs nothing?" },
	"What moment made you proud of us as a team?",
	"What's your favorite nickname between us and why?",
	{ ldr: "When do you feel closest to me despite the kilometers?",
	  together: "When do you feel closest to me?" },

	// Would you rather (couple edition)
	"Would you rather live in my city together or yours — first?",
	{ ldr: "Would you rather have one month together now, or two weeks twice this year?",
	  together: "Would you rather one long trip a year, or lots of little weekends away?" },
	"Would you rather read all my thoughts for a day, or me read yours?",
	"Would you rather never text again but call every day, or never call but text unlimited?",
	"Would you rather grow old by the sea or in a big city?",
	{ met: "Would you rather I surprise-visit you, or plan the visit together and count down?",
	  notMet: "Would you rather I surprise you for our first meeting, or plan it together and count down?" },
	"Would you rather cook for me or have me cook for you (be honest about my cooking)?",
	{ met: "Would you rather relive our first conversation or fast-forward to our reunion?",
	  notMet: "Would you rather relive our first conversation or fast-forward to the day we finally meet?" },

	// Daily life
	"What's the best thing that happened to you today, big or small?",
	"What did you eat today and should I be jealous?",
	"What's currently stuck in your head — song, worry, or idea?",
	{ ldr: "If I was there tonight, what would we be doing right now?",
	  together: "If tonight was ours with zero obligations, what would we be doing?" },
	"What made you think of me today?",
	"How's your heart today, from 1 to 10 — and why?",
	"What's one thing that annoyed you today that you can laugh about now?",
	"What are you wearing right now — style rating out of 10?",
	"What's the next small thing you're looking forward to?",
	"If today had a color, what color was it?",
];

/** @type {(string | { met: string, notMet: string })[]} */
export const SPICY_QUESTIONS = [
	{ met: "What do you miss the most about being physically close?",
	  notMet: "What do you think you'd love the most about being physically close?",
	  together: "What's your favorite thing about being physically close?" },
	{ met: "Where do you like being kissed that I might not know about yet?",
	  notMet: "Where would you love to be kissed first, the day we meet?" },
	"What's something innocent I do that secretly drives you crazy?",
	{ met: "Describe our reunion hug at the airport — every detail.",
	  notMet: "Describe our very first hug at the airport — every detail.",
	  together: "Describe your favorite hug of ours — every detail." },
	"What outfit of mine (real or imagined) would you love to see me in?",
	"What's a compliment about your body you'd love to hear more often?",
	"If I whispered one sentence in your ear right now, what do you hope it would be?",
	"What's your favorite way I say your name?",
	{ ldr: "Voice note or video call, when you miss me at night — and why?",
	  together: "Big spoon or little spoon tonight — and why?" },
	"What's the most attractive thing I've done without realizing it?",
	"What would you want our first morning together to be like?",
	"Which part of you do you want me to compliment more?",
	"What song would you put on if we were slow-dancing in my kitchen?",
	"What's a daydream about us you've never confessed?",
	"How would you distract me if I was trying to work and you were there?",
	"What's the flirtiest message you've almost sent me but deleted?",
	{ met: "Where would you want me to kiss you first when we meet again?",
	  notMet: "Where would you want me to kiss you first when we finally meet?",
	  together: "Where do you want me to kiss you first when you come home today?" },
	"What's something you find sexy that has nothing to do with looks?",
	"If we had one hour with no phones and no world, how would we spend it?",
	"What do my hands make you think about?",
	"What's your favorite thing about my voice when it gets late?",
	"Bath or shower — and are we sharing?",
	"What's a place (not the bedroom) where you'd love a very long kiss?",
	{ ldr: "What little sound of mine do you wish you could hear right now?",
	  together: "What little sound of mine are you secretly fond of?" },
	"What would you do if I appeared at your door in the rain, right now?",
	"Which of my photos do you look at more than you'd admit?",
	{ ldr: "What's the boldest thing you'd dare to do on our next video call?",
	  together: "What's the boldest thing you'd dare to do next time we're out together?" },
	"How do you want to be held on a bad day — show me with words?",
	"What part of our future together feels the most exciting when you think about it at night?",
	"Finish this sentence: 'When we're finally together, the first thing I'll do is…'",
];
